version: '3.8'
x-reusable-parts: &node-modules-volume
                    /usr/src/node-app/node_modules

services:
  node-app:
    build: .
    container_name: node-app
    image: node-app
    ports:
      - ${PORT}:8080
    depends_on:
      - postgresdb
    volumes:
      - .:/usr/src/node-app
      - *node-modules-volume
    networks:
      - node-network
    env_file:
      - ./.env

  postgresdb:
    image: postgres
    container_name: postgresdb
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - node-network

volumes:
  db_data:
    driver: local

networks:
  node-network:
    driver: bridge