version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    ports:
      - '8080:8080'
#    depends_on:
#      - postgresdb
    volumes:
      - .:/usr/src/node-app
      - /usr/src/node-app/node_modules
    networks:
      - node-network
    env_file:
      - ./.env

networks:
  node-network:
    driver: bridge