version: '3.8'
x-reusable-parts: &node-modules-volume
                    /usr/src/node-app/node_modules

services:
  node-app:
    build: .
    image: node-app
    ports:
      - ${PORT}:8080
    volumes:
      - .:/usr/src/node-app
      - *node-modules-volume
    networks:
      - node-network
    env_file:
      - ./.env
networks:
  node-network:
    driver: bridge