
version: '3.8'
services:
  postgresdb:
    image: postgres
    restart: always
    container_name: postgresdb-util-test
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local